version: 2.1

references:
  container_config: &container_config
    docker:
      - image: node:16

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: npm ci
      - run: npm run build -- --mode mock
  lint:
    <<: *container_config
    steps:
      - checkout
      - run: npm install --only=dev
      - run: npm run lint
  test_e2e:
    <<: *container_config
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: npm install --only=dev
      - run:
          command: npm run serve:mocked
          background: true
      - run: npx cypress install
      - run:
          command: |
            npx wait-on http://localhost:8080
            npm run test:e2e:ci
      - store_test_results:
          path: /home/circleci/project/integration/results

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test_e2e:
          requires:
            - build
